# This compose file will deploy the services, and bootup a mongo server.

# Copyright IBM Corp., All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Local `/opt/cello/mongo` will be used for the db storage.
#  dashboard: dashboard service of cello, listen on 8080
#  app: app service of cello, listen on 80
#  nginx: front end
#  mongo: mongo db

version: '2'
services:
  # cello dashboard service
  npm-install:
    image: node:9.3
    volumes:  # This should be removed in product env
      - $ROOT_PATH/src/$STATIC_FOLDER:/app
    environment:
      - NPM_REGISTRY=$NPM_REGISTRY
    command: bash -c "cd /app && npm install --loglevel http --registry $NPM_REGISTRY"
