# This compose file will deploy the services, and bootup a mongo server.

# Copyright IBM Corp., All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Local `/opt/cello/mongo` will be used for the db storage.
#  dashboard: dashboard service of cello, listen on 8080
#  app: app service of cello, listen on 80
#  nginx: front end
#  mongo: mongo db

version: '3.2'
services:
  # cello dashboard service
  dashboard:
    build:
      context: src
      dockerfile: Dockerfile-dashboard
    image: hyperledger/cello-dashboard
    container_name: dashboard
    hostname: cello-dashboard
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB=dev
      - DEBUG=True    # in debug mode, service will auto-restart
      - LOG_LEVEL=DEBUG  # what level log will be output
      - STATIC_FOLDER=$STATIC_FOLDER
      - TEMPLATE_FOLDER=$TEMPLATE_FOLDER
      - ENABLE_EMAIL_ACTIVE=$ENABLE_EMAIL_ACTIVE
    expose:
      - "8080"
    volumes:  # This should be removed in product env
      - ./src:/app

  # cello restserver service
  restserver:
    build:
      context: src
      dockerfile: Dockerfile-restserver
    image: hyperledger/cello-restserver
    container_name: restserver
    hostname: cello-restserver
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB=dev
      - DEBUG=True    # in debug mode, service will auto-restart
      - LOG_LEVEL=DEBUG  # what level log will be output
    expose:
      - "80"
    volumes:  # This should be removed in product env
      - ./src:/app

  # cello watchdog service
  watchdog:
    build:
      context: src
      dockerfile: Dockerfile-watchdog
    image: hyperledger/cello-watchdog
    container_name: watchdog
    hostname: cello-watchdog
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB=dev
      - DEBUG=True    # in debug mode, service will auto-restart
      - LOG_LEVEL=DEBUG  # what level log will be output
    volumes:  # This should be removed in product env
      - ./src:/app

  # mongo database, may use others in future
  mongo:
    image: hyperledger/cello-mongo
    hostname: mongo
    container_name: mongo
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
        reservations:
          cpus: '0.10'
          memory: 256M
    ports:
      #- "27017:27017"  # use follow line instead in production env
      - "127.0.0.1:27017:27017"
      - "127.0.0.1:27018:27018"
    environment:
      - NO_USED=0
    volumes:
      - /opt/cello/mongo:/data/db

  # nginx to forward front request, may split it out in future
  nginx:
    image: hyperledger/cello-nginx
    hostname: nginx
    container_name: nginx
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
        reservations:
          cpus: '0.10'
          memory: 256M
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.default.conf
      #- /opt/cello/nginx/log/:/var/log/nginx/
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - BACKEND=dashboard
      - PORT=8080
      - USERNAME=admin
      - PASSWORD=pass

 #TODO: need to follow other images to put at dockerhub
  user-dashboard:
    build:
      context: user-dashboard
    image: hyperledger/cello-user-dashboard
    container_name: user-dashboard
    links:
      - mongo:dashboard_mongo
      - dashboard
    ports:
      - "8081:8080"
    environment:
      - SV_BaseURL=http://dashboard:8080/api/
      - RESTful_Server=dashboard:8080
      - RESTful_BaseURL=/api/v2/
      - DEBUG=node:*
      - DEV=$DEV
      - ENABLE_EMAIL_ACTIVE=$ENABLE_EMAIL_ACTIVE
      - SMTP_SERVER=$SMTP_SERVER
      - SMTP_PORT=$SMTP_PORT
      - SMTP_AUTH_USERNAME=$SMTP_AUTH_USERNAME
      - SMTP_AUTH_PASSWORD=$SMTP_AUTH_PASSWORD
      - FROM_EMAIL=$FROM_EMAIL
      - WEBROOT=$WEBROOT
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
    volumes:
      - ./user-dashboard:/usr/app/src
    command: bash -c "cd /usr/app/src && [ "$DEV" = True ] && npm run dev || npm start"
