---
- name: Setup variables
  set_fact:
    goroot: "/opt/go"
    gopath: "/opt/gopath/{{ env }}"
    fabricpath: "/opt/gopath/{{ env }}/src/github.com/hyperledger/fabric"

- name: Setup hyperledger directory
  file:
    path: "{{ fabricpath }}"
    state: directory
    mode: 0775

- name: Clean targets
  command: make clean
  args:
    chdir: "{{ fabricpath }}"
  register: result
  environment:
    GOROOT: "{{ goroot }}"
    GOPATH: "{{ gopath }}"
    PATH: "{{ ansible_env.PATH}}:{{ goroot }}/bin"
  tags: "clean"
