---
- name: Setup /etc/hosts for the node
  lineinfile:
    dest: "/etc/hosts"
    insertafter: EOF
    state: present
    line: "{{ item }}"
  with_lines: cat "{{ playbook_dir }}/../../vars/fabrichosts"