---
- name: Setup variables
  set_fact:
    fabricpath: "{{ pjroot }}/vars/{{ env }}"

- stat:
    path: "{{ fabricpath }}/bin/cryptogen"
  register: binexists

- name: Download fabric binaries
  unarchive:
    src: "{{ fabric.repo.bin }}"
    dest: "{{ fabricpath }}"
    exclude: ["config"]
    remote_src: yes
  when: fabric.repo.bin|length > 0 and binexists.stat.exists == false
  tags: "downloadbin"

- name: Download kubectl
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v1.10.2/bin/linux/amd64/kubectl"
    dest: "{{ playbook_dir }}/../../vars/kubectl"
    mode: 0755
  tags: "downloadbin"
