---
- name: Setup /etc/hosts for the node
  lineinfile:
    dest: "/etc/hosts"
    insertafter: EOF
    state: present
    line: "{{ item }}"
  with_lines: cat "{{ playbook_dir }}/../../vars/fabrichosts"

- name: Change the host name
  shell: >-
    echo {{ inventory_hostname[3:] }} > /etc/hostname;
    hostname {{ inventory_hostname[3:] }}
