---
- name: build fabric artifacts
  hosts: builders
  gather_facts: true
  user: "{{ fabric.ssh_user }}"
  vars_files:
    - "./../../vars/{{ env }}.yml"
  tasks:
    - include_tasks: "fabricbuild/tasks/{{ mode }}.yml"
  tags: "fabricbuild"

- name: generate certificates
  hosts: builders
  gather_facts: false
  user: "{{ fabric.ssh_user }}"
  vars_files:
    - "./../../vars/{{ env }}.yml"
  tasks:
    - include: "certsetup/tasks/{{ mode }}.yml"
  tags: "certsetup"

- name: setup fabric network
  hosts: allnodes
  gather_facts: false
  user: "{{ fabric.ssh_user }}"
  vars_files:
    - "./../../vars/{{ env }}.yml"
  tasks:
    - include: "fabricsetup/tasks/{{ mode }}.yml"
  tags: "fabricsetup"

- name: setup composer
  hosts: builders
  gather_facts: false
  user: "{{ fabric.ssh_user }}"
  vars_files:
    - "./../../vars/{{ env }}.yml"
  tasks:
    - include: "composersetup/tasks/{{ mode }}.yml"
  tags: "composersetup"
