---
- name: Get start timestamp
  hosts: cloud
  connection: local
  tasks:
    - set_fact:
        starttime: "{{ ansible_date_time }}"

- name: Run the plays
  vars:
    env: "aws"
    cloud_type: "aws"
  include: "roles/cloud_aws/plays.yml"

- name: Run the plays
  vars:
    env: "aws"
    env_type: "flanneld"
  include: "roles/env_flanneld/plays.yml"

- name: Run the plays
  vars:
    env: "bc1st"
    deploy_type: "compose"
  include: "roles/deploy_compose/plays.yml"

- name: Inform the installer
  hosts: cloud
  connection: local
  tasks:
    - debug:
        msg: >-
          The work load started at {{ hostvars.cloud.starttime.time }},
          ended at {{ ansible_date_time.time }}
