---
- name: Reuse common code
  include_tasks: "{{ playbook_dir }}/../common/config_apply.yml"

- name: Remove fabric client pod
  command: >-
    ./kubectl --kubeconfig='kubeconfig' delete -f {{ pjrun }}/cli-k8s.yaml
  args:
    chdir: "{{ playbook_dir }}/../../vars/"
  when: (allorderers | length > 0) and (allpeers | length > 0)
  tags: "clientdown"

- name: Stop fabric pod and chaincode endpoint daemon set
  command: >-
    ./kubectl --kubeconfig='kubeconfig' delete -f {{ pjrun }}/{{ item }}
  args:
    chdir: "{{ playbook_dir }}/../../vars/"
  with_items:
    - "fabric-pod.yml"
    - "chainep.yaml"
  tags: "fabricdown"

- name: Reuse common code
  include_tasks: "{{ playbook_dir }}/../common/config_destroy.yml"
