---
# The url to the fabric source repository
GIT_URL: "http://gerrit.hyperledger.org/r/fabric"

# The gerrit patch set reference, should be automatically set by gerrit
# GERRIT_REFSPEC: "refs/changes/23/11523/3" # 1.0.0
# GERRIT_REFSPEC: "refs/changes/47/12047/3" # 1.0.1
# GERRIT_REFSPEC: "refs/changes/13/13113/1"
# GERRIT_REFSPEC: "refs/tags/v1.0.4" # 1.0.4
GERRIT_REFSPEC: "refs/tags/v1.0.5" # 1.0.5

# This variable defines fabric network attributes
fabric: {

  # The user to connect to the server
  ssh_user: "ubuntu",

  # options are "goleveldb", "CouchDB", default is goleveldb
  peer_db: "CouchDB",
  tls: false,
  logging_level: "ERROR",
  k8s: {
    exposeserviceport: False,
    storageclass: "default",
    storagecapacity: "2Gi",
    shared_storage: false,
    mem_req: "512Mi",
    mem_limit: "1024Mi",
    cpu_req: "0.1",
    cpu_limit: "0.2"
  },

  # The following section defines how the fabric network is going to be made up
  # cas indicates certificate authority containers
  # peers indicates peer containers
  # orderers indicates orderer containers
  # kafka indicates kafka containers
  # all names must be in lower case. Numeric characters cannot be used to start
  # or end a name. Character dot (.) can only be used in names of peers and orderers.
  network: {
    fabric001: {
      cas: ["ca1st.orga"],
      peers: ["anchor@peer1st.orga", "anchor@peer1st.orgb"],
      orderers: ["orderer1st.orgc", "orderer1st.orgd"],
      zookeepers: ["zookeeper1st"],
      kafkas: ["kafka1st"]
    },
    fabric002: {
      cas: ["ca1st.orgb"],
      peers: ["worker@peer2nd.orga", "worker@peer2nd.orgb"],
      orderers: ["orderer2nd.orgc", "orderer2nd.orgd"],
      zookeepers: ["zookeeper2nd"],
      kafkas: ["kafka2nd"]
    },
    fabric003: {
      cas: ["ca1st.orgc", "ca1st.orgd"],
      peers: ["worker@peer3rd.orga", "worker@peer3rd.orgb"],
      orderers: [],
      zookeepers: ["zookeeper3rd"],
      kafkas: ["kafka3rd"]
    }
  },

  # the container tag for main fabric components such as orderer, peer,
  # tools and chaincode. If left blank, then fabric components will be built
  # from the latest fabric source code with the combination of the refspec
  # specified above. If it is not empty, then its values must be the full
  # container tag like the following:
  #     x86_64-1.1.0-alpha                         # alpha release
  #     DAILY_STABLE                               # daily stable
  #     DEV_STABLE                                 # dev stable
  #     s390x-0.4.2                                # release 0.4.2 for s390x
  #     048c91eb47812582f36665fbea3d7e0e68e396bf   # commit build
  #     x86_64-1.0.0-snapshot-8d3275f              # snapshot build
  baseimage_tag: "amd64-1.1.0",

  # The container tag for accessory fabric components such as ca, kafka,
  # zookeeper and couchdb. It has to be the full tag just like the
  # baseimage_tag
  helper_tag: "amd64-0.4.8",
  ca: { admin: "admin", adminpw: "adminpw", image_tag: "amd64-1.1.0" },

  # Only use this field when you have a docker repository.
  repo: {
    # the url defines docker hub project access point
    # official hub - url: "hyperledger/",
    # fabric build hub - url: "nexus3.hyperledger.org:10001/hyperledger/",
    url: "hyperledger/",
    username: "",
    password: "",

    # locations to download fabric binaries. This url should point to a
    # compressed such as tar or zip file which contains necessary binaries
    # such as configtxgen, configtxlator, cryptogen etc.
    bin: "https://nexus.hyperledger.org/content/repositories/releases/org/hyperledger/fabric/hyperledger-fabric/linux-amd64-1.1.0/hyperledger-fabric-linux-amd64-1.1.0.tar.gz"
  }
}
