---
# The url to the fabric source repository
GIT_URL: "http://gerrit.hyperledger.org/r/fabric"

# The gerrit patch set reference, should be automatically set by gerrit
GERRIT_REFSPEC: ""

# The following defines a fabric network with 2 peers, 1 orderer, 1 zookeeper and 1 kafka
# It also defines that the peers will be using goleveldb.
fabric: {

  ssh_user: "ubuntu",
  peer_db: "goleveldb",
  tls: true,
  logging_level: "ERROR",
  k8s: {
    storageclass: "default",
    storagecapacity: "2Gi",
    shared_storage: false,
    mem_req: "512Mi",
    mem_limit: "1024Mi",
    cpu_req: "0.1",
    cpu_limit: "0.2"
  },

  network: {
    fabric001: {
      peers: ["leader@peer1st.mad","anchor@peer2nd.mad"],
      orderers: ["orderer1st.sin"],
      zookeepers: ["zookeeper1st"],
      kafkas: ["kafka1st"]
    }
  },

  # the container tag for main fabric components such as orderer, peer,
  # tools and chaincode. If left blank, then fabric components will be built
  # from the latest fabric source code with the combination of the refspec
  # specified above. If it is not empty, then its values must be the full
  # container tag like the following:
  #     x86_64-1.1.0-alpha                         # alpha release
  #     DAILY_STABLE                               # daily stable
  #     DEV_STABLE                                 # dev stable
  #     s390x-0.4.2                                # release 0.4.2 for s390x
  #     048c91eb47812582f36665fbea3d7e0e68e396bf   # commit build
  #     x86_64-1.0.0-snapshot-8d3275f              # snapshot build
  baseimage_tag: "amd64-1.1.0",

  # The container tag for accessory fabric components such as ca, kafka,
  # zookeeper and couchdb. It has to be the full tag just like the
  # baseimage_tag
  helper_tag: "amd-0.4.8",
  ca: { admin: "admin", adminpw: "adminpw", image_tag: "amd64-1.1.0" },

  # Only use this field when you have a docker repository.
  repo: {
    # the url defines docker hub project access point
    # official hub - url: "hyperledger/",
    # fabric build hub - url: "nexus3.hyperledger.org:10001/hyperledger/",
    url: "hyperledger/",

    # locations to download fabric binaries. This url should point to a
    # compressed such as tar or zip file which contains necessary binaries
    # such as configtxgen, configtxlator, cryptogen etc.
    bin: "https://nexus.hyperledger.org/content/repositories/releases/org/hyperledger/fabric/hyperledger-fabric-build/linux-amd64-ff6f6dbffed57efb9f7d8886b4a47949ce2d4396/hyperledger-fabric-build-linux-amd64-ff6f6dbffed57efb9f7d8886b4a47949ce2d4396.tar.gz"
  }
}
