---
auth: {
  # Define where the VirtualBox(VB) system is
  auth_url: "192.168.0.35",
  # User name to log in to the remote VB system
  username: "tongli",
  # Password to the VB system, can specify at command line
  # or use env variable named PASSWORD
  password: "{{ password | default(lookup('env', 'password')) }}"
}

# This variable defines cloud provision attributes
cluster: {
  target_os: "ubuntu",
  image_name: "fabricbase",
  ssh_user: "ubuntu",
  ssh_pass: "ps",
  validate_certs: True,
  public_key_file: "/home/ubuntu/.ssh/fd.pub",
  private_key_file: "/home/ubuntu/.ssh/fd",
  # This variable indicate what IP should be used, only valid values are
  # private_ip or public_ip
  node_ip: "public_ip",

  container_network: {
    Network: "172.16.0.0/16",
    SubnetLen: 24,
    SubnetMin: "172.16.0.0",
    SubnetMax: "172.16.255.0",
    Backend: {
      Type: "ipip",
      DirectRouting: True
    }
  },

  service_ip_range: "172.15.0.0/16",
  dns_service_ip: "172.15.0.4",

  # the section defines preallocated IP addresses for each node, if there is no
  # preallocated IPs, leave it blank
  node_ips: ["169.45.102.186", "169.45.102.187", "169.45.102.188"],

  # fabric network node names expect to be using a clear pattern, this defines
  # the prefix for the node names.
  name_prefix: "fabric",
  domain: "fabricnet",

  # stack_size determines how many virtual or physical machines we will have
  # each machine will be named ${name_prefix}001 to ${name_prefix}${stack_size}
  stack_size: 2,

  etcdnodes: ["fabric001"],
  builders: ["fabric001"],

  flannel_repo: "https://github.com/coreos/flannel/releases/download/v0.10.0/flannel-v0.10.0-linux-amd64.tar.gz",
  etcd_repo: "https://github.com/coreos/etcd/releases/download/v3.3.2/etcd-v3.3.2-linux-amd64.tar.gz",
  k8s_repo: "https://storage.googleapis.com/kubernetes-release/release/v1.9.1/bin/linux/amd64/",
  go_repo: "https://dl.google.com/go/go1.9.2.linux-amd64.tar.gz",

  # If volume want to be used, specify a size in GB, make volume size 0 if wish
  # not to use volume from your cloud
  volume_size: 8
}
